---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learnserviceapi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: learnserviceapi
    spec:
      containers:
      - name: mymicroservice
        image: ruchinmunjal/learnserviceapi:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: http://*:80
  selector:
    matchLabels:
      app: learnserviceapi
---
apiVersion: v1
kind: Service
metadata:
  name: learnserviceapi
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: learnserviceapi
